# Generated by Django 4.2.7 on 2025-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
