# Generated by Django 4.2.7 on 2025-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_consumed_item_consumed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='warranty_until',
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('gut', 'Gut'), ('ok', 'OK'), ('schlecht', 'Schlecht')], default='gut', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, choices=[('wohnzimmer', 'Wohnzimmer'), ('schlafzimmer', 'Schlafzimmer'), ('kueche', 'Küche'), ('bad', 'Bad'), ('buero', 'Büro'), ('keller', 'Keller'), ('dachboden', 'Dachboden'), ('garage', 'Garage'), ('balkon', 'Balkon'), ('sonstiges', 'Sonstiges')], max_length=50),
        ),
    ]
