# Generated by Django 4.2.7 on 2025-05-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_image_remove_item_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='item',
            name='current_value',
        ),
    ]
