# Generated by Django 4.2.7 on 2025-05-30 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_remove_condition_and_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN/UPC Barcode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='expected_lifetime_days',
            field=models.IntegerField(blank=True, help_text='Erwartete Lebensdauer in Tagen', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Ablaufdatum für Lebensmittel etc.', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reminder_days_before',
            field=models.IntegerField(default=3, help_text='Tage vor Ablauf für Erinnerung'),
        ),
        migrations.AddField(
            model_name='item',
            name='reminder_enabled',
            field=models.BooleanField(default=False, help_text='Erinnerungen für dieses Item aktivieren'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('expiry', 'Ablaufdatum'), ('maintenance', 'Wartung'), ('repurchase', 'Nachkauf')], max_length=20)),
                ('message', models.TextField()),
                ('reminder_date', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='inventory.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('monthly', 'Monatlich'), ('yearly', 'Jährlich')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='inventory.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'category', 'period')},
            },
        ),
    ]
