# Generated by Django 4.2.7 on 2025-05-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_barcode_item_expected_lifetime_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Anzahl der Items'),
        ),
    ]
