# Generated by Django 4.2.7 on 2025-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_quantity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL zum Produktbild', null=True),
        ),
    ]
