# Generated by Django 4.2.7 on 2025-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='initial_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Ursprüngliche Kaufmenge für Smart Suggestions', null=True),
        ),
    ]
