# Generated by Django 4.2.7 on 2025-06-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_initial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.CharField(blank=True, help_text='Einkaufsgeschäft (z.B. REWE, dm, LIDL)', max_length=100, null=True),
        ),
    ]
