# Generated by Django 4.2.7 on 2025-06-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_store_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expected_lifetime_days',
        ),
    ]
